services:
  gotify:
    container_name: gotify
    hostname: gotify
    image: gotify/server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - net
      - nginx-proxy-manager_default
    ports:
      - "8680:80"
    volumes:
      - ./gotify:/app/data    # Changed to bind mount
    environment:
      GOTIFY_DEFAULTUSER_PASS: 'Ajay2628'
      GOTIFY_URLS: 'http://gotify'
      GOTIFY_CLIENT_TOKENS: 'A7lDONMdj7plnhu'
      TZ: 'America/Guyana'

  igotify:
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pull_policy: always
    networks:
      - net
      - nginx-proxy-manager_default
    ports:
      - "8681:8080"
    environment:
      GOTIFY_URLS: 'http://gotify'
      GOTIFY_CLIENT_TOKENS: 'cXXXXXXXX'
      TZ: 'America/Guyana'

networks:
  net:
  nginx-proxy-manager_default:
    external: true
